package layer.kernel;

public enum CandidateType {
    CANDIDATE_ANSWER,
    CANDIDATE_BELIEF,
    CANDIDATE_PLAN,
    TASK_DECOMPOSITION,
    ACTION_PROPOSAL,
    TOOL_CALL_PROPOSAL,
    GROUNDED_FACT,
    MEMORY_USE,
    REFLECTION_NOTE,
    POLICY_DECISION,
    ADMISSIBILITY_DECISION,
    EXPLANATION
}
